#!/usr/bin/env bash
#
# Project Bootstrap Script
# Automates greenfield repository provisioning, boilerplate cleaning, remote binds,
# and safe copying of process templates without git metadata duplication.
#
# Usage:
#   bootstrap.sh <project_name> <github_repo_url> [--process <process_slug>] [--scaffold <framework>]
#

set -euo pipefail

# Helper to log output
log() {
  echo -e "\033[1;32m[Bootstrap]\033[0m $1"
}

log_err() {
  echo -e "\033[1;31m[Error]\033[0m $1" >&2
}

# Print usage
usage() {
  echo "Usage: $0 <project_name> <github_repo_url> [--process <process_slug>] [--scaffold <framework>]"
  echo ""
  echo "Arguments:"
  echo "  project_name     Name of the project directory (created under ~/projects/)"
  echo "  github_repo_url  The GitHub remote repository URL to bind"
  echo ""
  echo "Options:"
  echo "  --process        Process template to copy from ~/.gemini/config/workspace/templates/ (default: sdd-process)"
  echo "  --scaffold       Framework boilerplate to scaffold: 'nextjs', 'python', or 'none' (default: none)"
  exit 1
}

# Parse arguments
if [ "$#" -lt 2 ]; then
  usage
fi

PROJECT_NAME="$1"
GITHUB_REPO_URL="$2"
PROCESS_SLUG="sdd-process"
SCAFFOLD="none"

shift 2

while [ "$#" -gt 0 ]; do
  case "$1" in
    --process)
      PROCESS_SLUG="$2"
      shift 2
      ;;
    --scaffold)
      SCAFFOLD="$2"
      shift 2
      ;;
    *)
      log_err "Unknown parameter: $1"
      usage
      ;;
  esac
done

if [[ "$PROJECT_NAME" =~ ^[./] ]]; then
  PROJECT_DIR="$(readlink -f "$PROJECT_NAME")"
else
  PROJECT_DIR="$HOME/projects/$PROJECT_NAME"
fi
TEMPLATES_DIR="${GEMINI_WORKSPACE_DIR:-${GEMINI_TEMPLATES_DIR:-$HOME/.gemini/config/workspace}}/templates/$PROCESS_SLUG"

# 1. Validation Checks
if [ -d "$PROJECT_DIR" ]; then
  log_err "Directory already exists: $PROJECT_DIR"
  exit 1
fi

if [ ! -d "$TEMPLATES_DIR" ]; then
  log_err "Process template not found: $TEMPLATES_DIR"
  log_err "Please ensure your workspace templates are symlinked to ~/.gemini/config/workspace/ first:"
  log_err "  mkdir -p ~/.gemini/config/"
  log_err "  ln -s ~/projects/ag-setup/workspace/ ~/.gemini/config/workspace"
  exit 1
fi

# 2. Create Workspace Directory & Init Git
log "Creating project folder at $PROJECT_DIR..."
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

log "Initializing Git repository..."
git init

# 3. Scaffolding Frameworks (if specified)
if [ "$SCAFFOLD" = "nextjs" ]; then
  log "Scaffolding Next.js boilerplate (non-interactive)..."
  # Run create-next-app in the current folder without prompting
  npx --yes create-next-app@latest . --ts --eslint --tailwind --src-dir --no-import-alias --app --use-npm
elif [ "$SCAFFOLD" = "python" ]; then
  log "Scaffolding basic Python workspace..."
  mkdir -p src tests/unit tests/integration docs
  python3 -m venv .venv
  echo "# Requirements" > requirements.txt
  echo "pytest" >> requirements.txt
  echo "pydocstyle" >> requirements.txt
  echo "mdformat" >> requirements.txt
  echo "src/" > .gitignore
  echo ".venv/" >> .gitignore
  echo "__pycache__/" >> .gitignore
fi

# 4. Recursively clean any nested .git metadata generated by frameworks
log "Cleaning nested framework .git artifacts..."
find . -mindepth 2 -name ".git" -type d -exec rm -rf {} + || true

# 5. Bind Git Remote Origin
log "Configuring remote Git origin..."
git remote add origin "$GITHUB_REPO_URL"

# 6. Safe Template RSync copying without git history metadata duplication
log "Safely copying $PROCESS_SLUG process templates to .agents/..."
mkdir -p .agents
rsync -av --exclude='.git' "$TEMPLATES_DIR/_agents/" ".agents/"

# 7. Setup GitIgnore additions
log "Updating .gitignore to exclude local agent telemetry and worktree files..."
cat << 'EOF' >> .gitignore

# Jetski / Antigravity Custom Folders
.agents/history/checkpoint.md
.docs_build/
worktrees/
spec_change_proposal.md
EOF

log "Initialization complete! Project scaffolded successfully at $PROJECT_DIR."

# 8. Open the new workspace in a new window (if code CLI is available)
if command -v code >/dev/null 2>&1; then
  log "Launching new IDE window for workspace: $PROJECT_DIR..."
  code -n "$PROJECT_DIR"
else
  log "Note: 'code' command-line tool not found in PATH. Please open $PROJECT_DIR manually."
fi

log "Next steps: Switch to your new window, start a new chat, and begin the SDD discovery process!"
